apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast-app-deployment  # Name of the deployment
spec:
  selector:
    matchLabels:
      app: weatherforecast-app  # Label selector to match pods controlled by this deployment
  template:
    metadata:
      labels:
        app: weatherforecast-app  # Labels applied to pods created by this deployment
    spec:
      containers:
        - name: weatherforecast-app  # Name of the container
          image: web-api:latest  # Docker image to use
          imagePullPolicy: Never
          ports:
          - containerPort: 80  # Port to expose within the pod
          resources:
            requests:
              memory: 20Mi
              cpu: "0.25"
            limits:
              memory: 400Mi
              cpu: "1"
